### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**
Closes https://github.com/conda-forge/git-feedstock/pull/18

### CODE REVIEW

**Comment by jjhelmus** [comment]
Can someone restart the AppVeyor build?

**Comment by ocefpaf** [comment]
Will do soon. I am canceling all builds now b/c they are all stuck. Except for staged-recipes. I am trying to debug this by cancelling all and triggering only one at a time. (Fun isn't :smile: )

**Comment by jakirkham** [comment]
Restarted.

**Comment by jakirkham** [comment]
Seems to still fail.

```python
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 151, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 412, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 355, in execute
    debug=args.debug)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 650, in build
    preserve_egg_dir=bool(m.get_value('build/preserve_egg_dir')))
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 194, in post_process
    compile_missing_pyc(files)
  File "C:\Miniconda\lib\site-packages\conda_build\post.py", line 189, in compile_missing_pyc
    call([python_exe, '-Wi', '-m', 'py_compile', f], cwd=cwd)
  File "C:\Miniconda\lib\subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Miniconda\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "C:\Miniconda\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

@msarahan do you have any suggestions for us?

**Comment by jakirkham** [comment]
Thanks for the suggestion Mike. Have pushed a commit that should do the trick.

**Comment by jakirkham** [comment]
FWICT adding `python` to the build requirements does solve it. Here is the [build]( https://ci.appveyor.com/project/jakirkham/git-feedstock/build/1.0.3 ) from my fork. Expect this will pass too once the AppVeyor queue clears a bit.

Opened issue ( https://github.com/conda/conda-build/issues/1587 ) to address this bug.

**Comment by jakirkham** [comment]
Also cherry-picked the changes from PR ( https://github.com/conda-forge/git-feedstock/pull/18 ) to adjust the pinnings. As they are minor changes, seemed worthwhile to get them rolled into this.

**Comment by jakirkham** [comment]
Given I have modified this a bit, anyone else have thoughts on these changes?

**Comment by jjhelmus** [comment]
LGTM

**Pull request merged**
