### PR TITLE
install completions for Bash

### PR DESCRIPTION
**Pull request by scopatz**
This has to be done manually.

### CODE REVIEW

**Comment by scopatz** [comment]
Looks like this works!

**Comment by jakirkham** [comment]
SGTM.

Could we test this somehow? Presumably activating it. I guess actually using the autocompletion may prove tricky. So we can forego that part unless you have any clever ideas.

**Comment by scopatz** [comment]
We could run the file.  That would probably be enough.  Actually running a completion command is pretty annoying :) But running the file would ensure that it is valid.

**Comment by scopatz** [comment]
OK @jakirkham - test added!

**Comment by jakirkham** [comment]
Yep, that's what I was meaning. Sorry if that was unclear.

**Comment by jdblischak** [comment]
What is the status of this PR? Including the Bash completion script would be convenient. I was able to use the recipe in this PR to build and install Git on macOS 10.10.5 (Yosemite), and then enabled Bash completion with `source <path-to-environment>/share/bash-completion/completions/git`. The main issue I can see is that this PR edits the recipe for version 2.12.2, but the current recipe is for 2.13.3.

**Comment by jakirkham** [comment]
I think it was merely forgotten (by me). There was minor merge conflict w.r.t. the `build/number`, which I have taken the liberty of resolving. Happy to merge once it passes.

**Comment by scopatz** [comment]
Wow, I forgot that I even put this in :)

**Comment by jakirkham** [comment]
Maybe this should be merged after the update ( https://github.com/conda-forge/git-feedstock/pull/26 ) though to avoid conflicts with that PR. Thoughts?

**Comment by scopatz** [comment]
Well, this one went it first  (by over a month). But frankly, I am happy as long as the commits here get in.

**Comment by jakirkham** [comment]
Right. Not trying to delay this further. Definitely plan to merge one right after the other. Just if we merge this first, it will introduce a conflict/extra step for the update PR. Whereas if we merge this after, we can just merge them back to back without issues. Does that seem reasonable?

**Comment by scopatz** [comment]
Yes, that makes sense! I am all for whatever is easiest

**Comment by jakirkham** [comment]
Thanks @scopatz!

**Pull request merged**
