### PR TITLE
Cleanup and fixes

### PR DESCRIPTION
**Pull request by jakirkham**
Absorbs this cleanup PR ( https://github.com/conda-forge/git-feedstock/pull/2 ) and addition of @msarahan and @pelson. Also, adds `autoconf` to the dependencies.

### CODE REVIEW

**Comment by jakirkham** [comment]
Yep, adding `autoconf` seems to help.

**Comment by jakirkham** [comment]
Ouch, [hitting]( https://travis-ci.org/conda-forge/git-feedstock/builds/124251710#L1191 ) the max header length on Mac. Will need something like this PR ( https://github.com/conda/conda-build/pull/877 ) to fix it. Might try not using `autoconf` on Mac, but that feels disgusting.

**Comment by pelson** [comment]
Any idea how this built the first time around?

**Comment by jakirkham** [comment]
That is a fair question that I don't have a 100% certain answer for. However, since this was added, we have rebuilt many of its dependencies here. Maybe we need to pin them to Continuum versions and investigate these packages one by one.

**Comment by jakirkham** [comment]
Really confused as to how this has started failing recently. @msarahan would you mind taking a look at this?

**Comment by jakirkham** [comment]
Seems bumping the version did the trick. Merging so that we can get this operational again.

**Pull request merged**
