### PR TITLE
OLD: NO MRG: Use certs for Unix platforms

### PR DESCRIPTION
**Pull request by jakirkham**
Pulled from this nice work ( https://github.com/conda-forge/git-feedstock/pull/6 ) by @msarahan. Required some tweaks to remove MSYS2 stuff for now and to remove conflicts.

The `certifi` package provides certs as pointed at by @groutr. This is the simplest way for us to get them. So, we just install them and configure `git` to use them. This is only necessary for UNIX as PortableGit ships with certs.

### CODE REVIEW

**Comment by pelson** [comment]
Are you able to come up with a test @jakirkham?

**Comment by jakirkham** [comment]
> Are you able to come up with a test @jakirkham?

Might be tricky. I think all the VMs have certs on them. Was going to try to test it locally. We can add a test that I find works, but it will be a false positive in the CIs.

We will ultimately want to use this `git` in the docker image instead of yum installing it. At which point, that should be a good test.

**Comment by msarahan** [comment]
I recommend checking out an https git repository

**Comment by jakirkham** [comment]
> I recommend checking out an https git repository

Of course, that's not the tricky part. The problem is if the CIs have certs. `git` will try to use them anyways. So, this test will be a false indicator. In the docker image, we install `git` with `yum`, which pulls certs. On Travis CI, they have `git` with certs too. So, it is hard to say we proved anything.

**Comment by msarahan** [comment]
Did you not copy the part of the recipe modification that tells git where
to look for certs?

**Comment by msarahan** [comment]
You did.  See https://github.com/conda-forge/git-feedstock/pull/7/files#diff-44a73bcc045c193c3bd45da87994b03bR26

**Comment by jakirkham** [comment]
Yes, I did, but I'm pretty sure it will fallback if it can't find them, no?

**Comment by msarahan** [comment]
I don't think so.  This is why the mac build of git was so broken.

**Comment by msarahan** [comment]
oh, sorry - I think it might on linux, but mac should still be a good test.

**Comment by jakirkham** [comment]
I believe Mac worked fine before. Anyways. Still will test it locally and still will add a test here. Just suggesting we don't trust it too much initially.

We could add some sort of hack that deletes the certs on the VMs. Then it would be a good test for sure. That's what I'm trying locally.

**Comment by pelson** [comment]
Advice: write the test before fixing it. We will know then if it fails or not.

**Comment by jakirkham** [comment]
So, I have played around with this a bit and I don't think `certifi` is necessary. It appears `openssl` has certs that come with it. In fact, the configuration provided here appears to use `openssl`'s certs and not `certifi`'s.

**Comment by msarahan** [comment]
The openssl package in defaults does include a cert, but you should not
assume it.  I have removed it in our openssl package.

**Comment by jakirkham** [comment]
> I have removed it in our openssl package.

Are you sure? I still see them. Will this appear in the next build then?

Well, we still need a package that provides the certs because `certifi` doesn't place them in the `$PREFIX/ssl` directory. Should be trivial to make though.

**Comment by msarahan** [comment]
So maybe I just got very confused with the certifi package - I thought it
was the one creating $PREFIX/ssl.  If that is not the case, I need to
reconsider this.

By "our openssl" I mean conda-forge's.

Regardless, I think certs should be independent of openssl.  They can, and
do, change independently of openssl, and throwing them together is not
helpful.

**Comment by jakirkham** [comment]
> So maybe I just got very confused with the certifi package - I thought it was the one creating $PREFIX/ssl. If that is not the case, I need to reconsider this.

It isn't. Though this is not a problem. I'm writing a recipe to copy them from certifi and place them there.

> By "our openssl" I mean conda-forge's. 

Ah. No that's fine. Let me make a certificates package and you can depend on it if you want there.

> Regardless, I think certs should be independent of openssl. They can, and do, change independently of openssl, and throwing them together is not helpful.

There should be an independent package yes. Though I think it is important to have them installed with openssl. In other words, they should be a run time dependency.

**Comment by jakirkham** [comment]
See this PR ( https://github.com/conda-forge/staged-recipes/pull/563 ) for progress.

**Comment by jakirkham** [comment]
Alright, since the certs are now packaged in `ca-certificates` and `openssl` pulls them in as a run time dependency, we are in good shape for picking this back up. Am going to start working on it now.

**Comment by jakirkham** [comment]
So, I'm really close, but I'm hitting a really nasty problem and would really appreciate thoughts on this one.

Basically, `curl` is hardcoding the path to the certs file in its libraries. I have tried all sorts of strategies to override it, but none of them stick. We can tell from the test failure. An excerpt of the failure can be seen below. This happens on *NIX builds. Can also be found in the [log]( https://travis-ci.org/conda-forge/git-feedstock/builds/131521534#L1605-L1606 ). Note how we have the `_build` and `_test` paths. I have made some changes to the tests so more info can be found in newer logs so that others can see this is the problem. My suspicion is we will need to fix these hardcoded paths in `curl`. Here is a PR ( https://github.com/conda-forge/curl-feedstock/pull/3 ) to do that exactly. Feedback welcome. 

```
git clone https://github.com/conda-forge/git-feedstock
Cloning into 'git-feedstock'...
fatal: unable to access 'https://github.com/conda-forge/git-feedstock/': error setting certificate verify locations:
  CAfile: /opt/conda/envs/_build/ssl/cacert.pem
  CApath: /opt/conda/envs/_test/ssl/cacert.pem
TESTS FAILED: git-2.8.2-1
```

**Comment by jakirkham** [comment]
HA! I think I fixed. 🎉 🎉 🎉

**Comment by jakirkham** [comment]
Passing. 😄

Not sure if we should do some rebasing here as this is pretty noisy. In any event, this is ready for review.

**Comment by jakirkham** [comment]
Yeah, I think I might start a fresh PR as this is kind of a mess.

**Comment by jakirkham** [comment]
Replacing by this PR ( https://github.com/conda-forge/git-feedstock/pull/10 ).

**Pull request closed without merging**
