### PR TITLE
Fix Windows package

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/git-feedstock/issues/4

Seems like there is something is going funny with the `git` build on Windows. This is an attempt to straighten it out.

cc @msarahan

### CODE REVIEW

**Comment by jakirkham** [comment]
Well, it does appear to at least be extracting the package now. That is a promising sign.

**Comment by jakirkham** [comment]
Alright, added a test that demonstrates the problem we are seeing (missing all of `git` on Windows). Fails appropriately on AppVeyor. Now that the CIs have finished will push the fix.

**Comment by jakirkham** [comment]
Now passing. 😄

**Comment by msarahan** [comment]
This looks fine, but I'd like to move towards using msys2's m2-git when we have the msys2-stuff-in-conda-forge-or-defaults issue worked out.

cc @mingwandroid

**Comment by jakirkham** [comment]
Sure. It sounds like @mingwandroid will be at our next meeting. So, that would be a great time to discuss this stuff. It is on the hackpad, but feel free to fill it out more as needed.

**Pull request merged**
