### PR TITLE
Git 2.24

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This would supersede #68.

### CODE REVIEW

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
Thanks!

**Comment by phil-blain** [comment]
Glad to help! Quick question: why did you also merge #68? I thought that as soon as it would be merged it would start building and uploading the package to conda-forge (which would fail because of the missing hashes)...
Is it because you merged this one immediately after so the package generation from #68 got cancelled somehow?

**Comment by scopatz** [comment]
because all of the commits in 68 are in this pr, 68 is counted as merged by github too

**Pull request merged**
