### PR TITLE
Fixes #82

### LINKED ISSUE #82: Recipe uses wrong ca-files according to conda documentation
According to [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/non-standard-certs.html) if `REQUESTS_CA_BUNDLE` is set should be used as default store. 

In the configuration the default conda ca-files are used and `REQUESTS_CA_BUNDLE ` is not considered.

https://github.com/conda-forge/git-feedstock/blob/14c0381b07d008a73e88ee8ca64631d499340b48/recipe/build.sh#L36

### PR DESCRIPTION
**Pull request by j-4**
Fixes #82 by checking if the REQUESTS_CA_BUNDLE env variable is set, otherwise use conda certificates.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by j-4** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
Seems reasonable to me

**Comment by scopatz** [comment]
Thanks @j-4!

**Comment by domste** [comment]
I have tried it and the changes did not fix the problem because the variable is read in the build step, but it needs to be set after "installation".

So the settings should be set post-linkage [via a post-linkage script](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html) such that git config is written during the installation process. 

I am preparing a PR.

**Pull request merged**
