### PR TITLE
Fixed bad lint, and added maintainers.

### PR DESCRIPTION
**Pull request by pelson**
Ping @msarahan - I've added you as a maintainer as you forked the repo 😉

### CODE REVIEW

**Comment by jakirkham** [comment]
Weird. I guess we now need `autoconf`. Maybe we were using it from the system before. Would you mind adding that, @pelson?

**Comment by jakirkham** [comment]
Making the fix with these changes included in this PR ( https://github.com/conda-forge/git-feedstock/pull/3 ).

**Comment by pelson** [comment]
Thanks @jakirkham!

**Comment by jakirkham** [comment]
Absorbed your recent changes in PR ( https://github.com/conda-forge/git-feedstock/pull/3 ).

**Pull request merged**
