### PR TITLE
Add htmldoc on [unix] and fix manpages on [osx]

### LINKED ISSUE #66: man pages on macOS
Issue: git man pages (added in #65) do not work on macOS. They are installed correctly to `$CONDA_PREFIX/man/man1` but are not shown by the commands `man git-$cmd`, `git help $cmd` or `git $cmd --help` (these commands show the man pages from the system git).

If I `export MANPATH=$CONDA_PREFIX/man/:$(manpath)` I can access correctly the man pages for git from conda.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at ~/miniconda3/envs/git2.23:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.9.11            hecc5488_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
git                       2.23.0          pl526hbdf3604_2    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                         0    conda-forge
libcxxabi                 9.0.0                         0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : git2.23
    active env location : ~/miniconda3/envs/git2.23
            shell level : 1
       user config file : ~/.condarc
 populated config files : ~/.condarc
          conda version : 4.7.10
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : ~/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : ~/miniconda3/pkgs
                          ~/.conda/pkgs
       envs directories : ~/miniconda3/envs
                          ~/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False

```
</details>

**EDIT** updated with the correct way to define MANPATH on macOS, per https://stackoverflow.com/a/53732044/6026237

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #66 

This PR adds the preformatted HTML Git documentation (`git help --web <command>`) and also adds symlinks from `$PREFIX/man/man?/` to  `$PREFIX/share/man/man?/` since the system `man` on macOS does not have the same logic as on Linux (see https://github.com/conda-forge/git-feedstock/issues/66#issuecomment-539095424).

### CODE REVIEW

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by phil-blain** [comment]
I tried re-rendering locally and it failed (see linked issue above in conda-smithy).

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Comment by phil-blain** [comment]
thanks @scopatz! any idea why the bot sometimes fail ?

**Comment by scopatz** [comment]
> any idea why the bot sometimes fail ?

yeah, sometimes a new version is released

**Comment by phil-blain** [comment]
I’ll fix the conflict with the correct hash for htmldocs for 2.24. 

I just had a thought: @dscho does `git help <command> --web` work on Windows ? I guess it’s all packaged in the git-for-windows download ?

**Comment by dscho** [comment]
> does `git help <command> --web` work on Windows ?

You mean `git help --web <command>` (the option must come before the command)? Yes, that works. `git help` even defaults to `--web` in Git for Windows.

> I guess it’s all packaged in the git-for-windows download ?

Yes.

**Comment by phil-blain** [comment]
@conda-forge-admin, please ping team

this is ready for review :)

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
This exploded the size of the linux artifact from 14 MB to 35 MB, FYI

**Comment by scopatz** [comment]
We should consider maybe moving the docs to a separate output

**Comment by phil-blain** [comment]
Oh! That would be the html documentation..
~~~bash
$ du -sh $CONDA_PREFIX/share/doc/git
15M     /users/.../anaconda3/envs/git/share/doc/git
~~~
although there is still 6MB missing...

I did not think about that (and surprised that it doubles the size of the package!). 

> We should consider maybe moving the docs to a separate output

Would that mean that a user would have to install two packages ? how does that work ? (I'm still learning the conda-forge ecosystem architecture!)

**Comment by phil-blain** [comment]
Also it would be cool if a bot could check the size increase automatically ! should I open a PR for that in regro  ?

**Comment by phil-blain** [comment]
Also I noticed that the htmldoc repo has both the html files and the txt files (asciidoc) used to generate the html, as well as all the Release notes for all Git versions. So maybe we could delete the txt files. That would save 5,4M.

**Pull request merged**
