### PR TITLE
Use new gettext outputs

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
`osx-64` needs https://github.com/conda-forge/osx-sysroot-feedstock/pull/1

**Comment by xhochy** [comment]
@conda-forge/git This is ready for review.

**Comment by xhochy** [comment]
@ocefpaf OK to merge this, too?

**Comment by ocefpaf** [comment]
Thanks for fixing gettext outputs everywhere!

**Pull request merged**
